var global_key ={
    nine_frame_key_du_doan: 'nine_frame_key_predict',
    money :[1.05,3.21,7.64,16.74,35.41,74,153,315],
    nine_frame_1st_frame: {
        ttt_key: 'nine_frame_1st_frame_ttt',
        ttf_key: 'nine_frame_1st_frame_ttf',
        tft_key: 'nine_frame_1st_frame_tft',
        tff_key: 'nine_frame_1st_frame_tff',
        ftt_key: 'nine_frame_1st_frame_ftt',
        ftf_key: 'nine_frame_1st_frame_ftf',
        fft_key: 'nine_frame_1st_frame_fft',
        fff_key: 'nine_frame_1st_frame_fff',
        curr_predicts : 'nine_frame_1st_curr_predicts',
        curr_index :'nine_frame_1st_curr_index',
        order_view : '1st_frame'
    },
    nine_frame_2st_frame: {
        ttt_key: 'nine_frame_2st_frame_ttt',
        ttf_key: 'nine_frame_2st_frame_ttf',
        tft_key: 'nine_frame_2st_frame_tft',
        tff_key: 'nine_frame_2st_frame_tff',
        ftt_key: 'nine_frame_2st_frame_ftt',
        ftf_key: 'nine_frame_2st_frame_ftf',
        fft_key: 'nine_frame_2st_frame_fft',
        fff_key: 'nine_frame_2st_frame_fff',
        curr_predicts : 'nine_frame_2st_curr_predicts',
        curr_index :'nine_frame_2st_curr_index',
        order_view : '2st_frame'
    },
    nine_frame_3st_frame: {
        ttt_key: 'nine_frame_3st_frame_ttt',
        ttf_key: 'nine_frame_3st_frame_ttf',
        tft_key: 'nine_frame_3st_frame_tft',
        tff_key: 'nine_frame_3st_frame_tff',
        ftt_key: 'nine_frame_3st_frame_ftt',
        ftf_key: 'nine_frame_3st_frame_ftf',
        fft_key: 'nine_frame_3st_frame_fft',
        fff_key: 'nine_frame_3st_frame_fff',
        curr_predicts : 'nine_frame_3st_curr_predicts',
        curr_index :'nine_frame_3st_curr_index',
        order_view : '3st_frame'
    },
    nine_frame_4st_frame: {
        ttt_key: 'nine_frame_4st_frame_ttt',
        ttf_key: 'nine_frame_4st_frame_ttf',
        tft_key: 'nine_frame_4st_frame_tft',
        tff_key: 'nine_frame_4st_frame_tff',
        ftt_key: 'nine_frame_4st_frame_ftt',
        ftf_key: 'nine_frame_4st_frame_ftf',
        fft_key: 'nine_frame_4st_frame_fft',
        fff_key: 'nine_frame_4st_frame_fff',
        curr_predicts : 'nine_frame_4st_curr_predicts',
        curr_index :'nine_frame_4st_curr_index',
        order_view : '4st_frame'
    },
    nine_frame_5st_frame: {
        ttt_key: 'nine_frame_5st_frame_ttt',
        ttf_key: 'nine_frame_5st_frame_ttf',
        tft_key: 'nine_frame_5st_frame_tft',
        tff_key: 'nine_frame_5st_frame_tff',
        ftt_key: 'nine_frame_5st_frame_ftt',
        ftf_key: 'nine_frame_5st_frame_ftf',
        fft_key: 'nine_frame_5st_frame_fft',
        fff_key: 'nine_frame_5st_frame_fff',
        curr_predicts : 'nine_frame_5st_curr_predicts',
        curr_index :'nine_frame_5st_curr_index',
        order_view : '5st_frame'
    },
    nine_frame_6st_frame: {
        ttt_key: 'nine_frame_6st_frame_ttt',
        ttf_key: 'nine_frame_6st_frame_ttf',
        tft_key: 'nine_frame_6st_frame_tft',
        tff_key: 'nine_frame_6st_frame_tff',
        ftt_key: 'nine_frame_6st_frame_ftt',
        ftf_key: 'nine_frame_6st_frame_ftf',
        fft_key: 'nine_frame_6st_frame_fft',
        fff_key: 'nine_frame_6st_frame_fff',
        curr_predicts : 'nine_frame_6st_curr_predicts',
        curr_index :'nine_frame_6st_curr_index',
        order_view : '6st_frame'
    },
    nine_frame_7st_frame: {
        ttt_key: 'nine_frame_7st_frame_ttt',
        ttf_key: 'nine_frame_7st_frame_ttf',
        tft_key: 'nine_frame_7st_frame_tft',
        tff_key: 'nine_frame_7st_frame_tff',
        ftt_key: 'nine_frame_7st_frame_ftt',
        ftf_key: 'nine_frame_7st_frame_ftf',
        fft_key: 'nine_frame_7st_frame_fft',
        fff_key: 'nine_frame_7st_frame_fff',
        curr_predicts : 'nine_frame_7st_curr_predicts',
        curr_index :'nine_frame_7st_curr_index',
        order_view : '7st_frame'
    },
    nine_frame_8st_frame: {
        ttt_key: 'nine_frame_8st_frame_ttt',
        ttf_key: 'nine_frame_8st_frame_ttf',
        tft_key: 'nine_frame_8st_frame_tft',
        tff_key: 'nine_frame_8st_frame_tff',
        ftt_key: 'nine_frame_8st_frame_ftt',
        ftf_key: 'nine_frame_8st_frame_ftf',
        fft_key: 'nine_frame_8st_frame_fft',
        fff_key: 'nine_frame_8st_frame_fff',
        curr_predicts : 'nine_frame_8st_curr_predicts',
        curr_index :'nine_frame_8st_curr_index',
        order_view : '8st_frame'
    },
    nine_frame_9st_frame: {
        ttt_key: 'nine_frame_9st_frame_ttt',
        ttf_key: 'nine_frame_9st_frame_ttf',
        tft_key: 'nine_frame_9st_frame_tft',
        tff_key: 'nine_frame_9st_frame_tff',
        ftt_key: 'nine_frame_9st_frame_ftt',
        ftf_key: 'nine_frame_9st_frame_ftf',
        fft_key: 'nine_frame_9st_frame_fft',
        fff_key: 'nine_frame_9st_frame_fff',
        curr_predicts : 'nine_frame_9st_curr_predicts',
        curr_index :'nine_frame_9st_curr_index',
        order_view : '9st_frame'
    },
    three_frame_combine_1st_2st_3st :{
        du_doan :'three_frame_combine_1st_2st_3st_du_doan',
        curr_3_before :'three_frame_combine_1st_2st_3st_curr_three_before',
        view_du_doan_id :'result_predict_1st_2st_3st_frame',
        curr_predicts :'three_frame_combine_1st_2st_3st_curr_predict',
        curr_index :'three_frame_combine_1st_2st_3st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_1st_2st_3st_frame',
        view_show_money_name:'money_predict_1st_2st_3st_frame',
        save_predict_3_combine:'result_predict_save_1st_2st_3st_frame',
        view_du_doan_next_next_id :'result_predict_next_next_1st_2st_3st_frame',
        curr_predicts_next :'three_frame_combine_1st_2st_3st_curr_predict_next',
        curr_index_next :'three_frame_combine_1st_2st_3st_curr_predict_index_next',
        du_doan_next :'three_frame_combine_1st_2st_3st_du_doan_next',
        curr_3_before_next :'three_frame_combine_1st_2st_3st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_1st_2st_3st_frame'
    },
    three_frame_combine_2st_3st_4st :{
        du_doan :'three_frame_combine_2st_3st_4st_du_doan',
        curr_3_before :'three_frame_combine_2st_3st_4st_curr_three_before',
        view_du_doan_id :'result_predict_2st_3st_4st_frame',
        curr_predicts :'three_frame_combine_2st_3st_4st_curr_predict',
        curr_index :'three_frame_combine_2st_3st_4st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_2st_3st_4st_frame',
        view_show_money_name:'money_predict_2st_3st_4st_frame',
        save_predict_3_combine: 'result_predict_save_2st_3st_4st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_2st_3st_4st_frame',
        curr_predicts_next: 'three_frame_combine_2st_3st_4st_curr_predict_next',
        curr_index_next: 'three_frame_combine_2st_3st_4st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_2st_3st_4st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_2st_3st_4st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_2st_3st_4st_frame'
    },
    three_frame_combine_3st_4st_5st :{
        du_doan :'three_frame_combine_3st_4st_5st_du_doan',
        curr_3_before :'three_frame_combine_3st_4st_5st_curr_three_before',
        view_du_doan_id :'result_predict_3st_4st_5st_frame',
        curr_predicts :'three_frame_combine_3st_4st_5st_curr_predict',
        curr_index :'three_frame_combine_3st_4st_5st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_3st_4st_5st_frame',
        view_show_money_name:'money_predict_3st_4st_5st_frame',
        save_predict_3_combine: 'result_predict_save_3st_4st_5st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_3st_4st_5st_frame',
        curr_predicts_next: 'three_frame_combine_3st_4st_5st_curr_predict_next',
        curr_index_next: 'three_frame_combine_3st_4st_5st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_3st_4st_5st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_3st_4st_5st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_3st_4st_5st_frame'
    },
    three_frame_combine_4st_5st_6st :{
        du_doan :'three_frame_combine_4st_5st_6st_du_doan',
        curr_3_before :'three_frame_combine_4st_5st_6st_curr_three_before',
        view_du_doan_id :'result_predict_4st_5st_6st_frame',
        curr_predicts :'three_frame_combine_4st_5st_6st_curr_predict',
        curr_index :'three_frame_combine_4st_5st_6st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_4st_5st_6st_frame',
        view_show_money_name:'money_predict_4st_5st_6st_frame',
        save_predict_3_combine: 'result_predict_save_4st_5st_6st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_4st_5st_6st_frame',
        curr_predicts_next: 'three_frame_combine_4st_5st_6st_curr_predict_next',
        curr_index_next: 'three_frame_combine_4st_5st_6st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_4st_5st_6st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_4st_5st_6st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_4st_5st_6st_frame'
    },
    three_frame_combine_5st_6st_7st :{
        du_doan :'three_frame_combine_5st_6st_7st_du_doan',
        curr_3_before :'three_frame_combine_5st_6st_7st_curr_three_before',
        view_du_doan_id :'result_predict_5st_6st_7st_frame',
        curr_predicts :'three_frame_combine_5st_6st_7st_curr_predict',
        curr_index :'three_frame_combine_5st_6st_7st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_5st_6st_7st_frame',
        view_show_money_name:'money_predict_5st_6st_7st_frame',
        save_predict_3_combine: 'result_predict_save_5st_6st_7st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_5st_6st_7st_frame',
        curr_predicts_next: 'three_frame_combine_5st_6st_7st_curr_predict_next',
        curr_index_next: 'three_frame_combine_5st_6st_7st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_5st_6st_7st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_5st_6st_7st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_5st_6st_7st_frame'
    },
    three_frame_combine_6st_7st_8st :{
        du_doan :'three_frame_combine_6st_7st_8st_du_doan',
        curr_3_before :'three_frame_combine_6st_7st_8st_curr_three_before',
        view_du_doan_id :'result_predict_6st_7st_8st_frame',
        curr_predicts :'three_frame_combine_6st_7st_8st_curr_predict',
        curr_index :'three_frame_combine_6st_7st_8st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_6st_7st_8st_frame',
        view_show_money_name:'money_predict_6st_7st_8st_frame',
        save_predict_3_combine: 'result_predict_save_6st_7st_8st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_6st_7st_8st_frame',
        curr_predicts_next: 'three_frame_combine_6st_7st_8st_curr_predict_next',
        curr_index_next: 'three_frame_combine_6st_7st_8st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_6st_7st_8st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_6st_7st_8st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_6st_7st_8st_frame'
    },
    three_frame_combine_7st_8st_9st :{
        du_doan :'three_frame_combine_7st_8st_9st_du_doan',
        curr_3_before :'three_frame_combine_7st_8st_9st_curr_three_before',
        view_du_doan_id :'result_predict_7st_8st_9st_frame',
        curr_predicts :'three_frame_combine_7st_8st_9st_curr_predict',
        curr_index :'three_frame_combine_7st_8st_9st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_7st_8st_9st_frame',
        view_show_money_name:'money_predict_7st_8st_9st_frame',
        save_predict_3_combine: 'result_predict_save_7st_8st_9st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_7st_8st_9st_frame',
        curr_predicts_next: 'three_frame_combine_7st_8st_9st_curr_predict_next',
        curr_index_next: 'three_frame_combine_7st_8st_9st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_7st_8st_9st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_7st_8st_9st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_7st_8st_9st_frame'
    },
    three_frame_combine_8st_9st_1st :{
        du_doan :'three_frame_combine_8st_9st_1st_du_doan',
        curr_3_before :'three_frame_combine_8st_9st_1st_curr_three_before',
        view_du_doan_id :'result_predict_8st_9st_1st_frame',
        curr_predicts :'three_frame_combine_8st_9st_1st_curr_predict',
        curr_index :'three_frame_combine_8st_9st_1st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_8st_9st_1st_frame',
        view_show_money_name:'money_predict_8st_9st_1st_frame',
        save_predict_3_combine: 'result_predict_save_8st_9st_1st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_8st_9st_1st_frame',
        curr_predicts_next: 'three_frame_combine_8st_9st_1st_curr_predict_next',
        curr_index_next: 'three_frame_combine_8st_9st_1st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_8st_9st_1st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_8st_9st_1st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_8st_9st_1st_frame'
    },
    three_frame_combine_9st_1st_2st :{
        du_doan :'three_frame_combine_9st_1st_2st_du_doan',
        curr_3_before :'three_frame_combine_9st_1st_2st_curr_three_before',
        view_du_doan_id :'result_predict_9st_1st_2st_frame',
        curr_predicts :'three_frame_combine_9st_1st_2st_curr_predict',
        curr_index :'three_frame_combine_9st_1st_2st_curr_predict_index',
        view_du_doan_next_id :'result_predict_next_9st_1st_2st_frame',
        view_show_money_name:'money_predict_9st_1st_2st_frame',
        save_predict_3_combine: 'result_predict_save_9st_1st_2st_frame',
        view_du_doan_next_next_id: 'result_predict_next_next_9st_1st_2st_frame',
        curr_predicts_next: 'three_frame_combine_9st_1st_2st_curr_predict_next',
        curr_index_next: 'three_frame_combine_9st_1st_2st_curr_predict_index_next',
        du_doan_next: 'three_frame_combine_9st_1st_2st_du_doan_next',
        curr_3_before_next: 'three_frame_combine_9st_1st_2st_curr_three_before_next',
        result_show_money_next :'result_show_money_next_9st_1st_2st_frame'
    }
};